[package]
name = "DESTRUCTION"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.34.0"
parser = { path = "../parser" }
interpreter = { path = "../interpreter" }
ariadne = "0.1.3"